package main

import (
	"log"

	"github.com/kornypoet/advent_of_code/calendar"
	"github.com/kornypoet/advent_of_code/util"
)

func main() {
	// log.Print("Day 1 part 1")
	// calendar.Day1(util.InputFromFile("input/day1.txt"), 1)
	// log.Print("Day 1 part 2")
	// calendar.Day1(util.InputFromFile("input/day1.txt"), 2)
	// log.Print("Day 2 part 1")
	// calendar.Day2(util.InputFromFile("input/day2.txt"), 1)
	// log.Print("Day 2 part 2")
	// calendar.Day2(util.InputFromFile("input/day2.txt"), 2)
	// log.Print("Day 3 part 1")
	// calendar.Day3(util.InputFromFile("input/day3.txt"), 1)
	// log.Print("Day 3 part 2")
	// calendar.Day3(util.InputFromFile("input/day3.txt"), 2)
	// log.Print("Day 4 part 1")
	// calendar.Day4(util.InputFromFile("input/day4.txt"), 1)
	// log.Print("Day 4 part 2")
	// calendar.Day4(util.InputFromFile("input/day4.txt"), 2)
	// log.Print("Day 5 part 1")
	// calendar.Day5(util.InputFromFile("input/day5.txt"), 1, nil)
	// log.Print("Day 5 part 2")
	// calendar.Day5(util.InputFromFile("input/day5.txt"), 2, nil)
	// log.Print("Day 6 part 1")
	// calendar.Day6(util.InputFromFile("input/day6.txt"), 1)
	// log.Print("Day 6 part 2")
	// calendar.Day6(util.InputFromFile("input/day6.txt"), 2)
	// log.Print("Day 7 part 1")
	// calendar.Day7(util.InputFromFile("input/day7.txt"), 1)
	// log.Print("Day 7 part 2")
	// calendar.Day7(util.InputFromFile("input/day7.txt"), 2)
	// log.Print("Day 8 part 2")
	// calendar.Day8(util.InputFromFile("input/day8.txt"), 1)
	// log.Print("Day 8 part 2")
	// calendar.Day8(util.InputFromFile("input/day8.txt"), 2)
	// log.Print("Day 9 part 1")
	// calendar.Day9(util.InputFromFile("input/day9.txt"), 1)
	// log.Print("Day 9 part 2")
	// calendar.Day9(util.InputFromFile("input/day9.txt"), 2)
	// log.Print("Day 10 part 1")
	// calendar.Day10(util.InputFromFile("input/day10.txt"), 1)
	// log.Print("Day 10 part 2")
	// calendar.Day10(util.InputFromFile("input/day10.txt"), 2)
	// log.Print("Day 11 part 1")
	// calendar.Day11(util.InputFromFile("input/day11.txt"), 1)
	// log.Print("Day 11 part 2")
	// calendar.Day11(util.InputFromFile("input/day11.txt"), 2)
	// TODO
	// log.Print("Day 12 part 1")
	// calendar.Day12(util.InputFromFile("input/day12.txt"), 1)
	// log.Print("Day 12 part 2")
	// calendar.Day12(util.InputFromFile("input/day12.txt"), 2)
	// log.Print("Day 13 part 1")
	// calendar.Day13(util.InputFromFile("input/day13.txt"), 1)
	// log.Print("Day 13 part 2")
	// calendar.Day13(util.InputFromFile("input/day13.txt"), 2)

	// log.Print("Day 14 part 1")
	// calendar.Day14(util.InputFromFile("input/day14.txt"), 1)
	log.Print("Day 14 part 2")
	calendar.Day14(util.InputFromFile("input/day14.txt"), 2)
}
